# Generated by Django 4.1.2 on 2022-10-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborg', '0002_myuser_is_agent_myuser_is_organiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome To Cyborg', max_length=150)),
                ('text', models.CharField(default='BROWSE OUR POPULAR GAMES HERE', max_length=200)),
                ('btn', models.CharField(default='Browse Now', max_length=50)),
            ],
        ),
    ]
