# Generated by Django 4.1.2 on 2022-10-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborg', '0003_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(default='game', max_length=100)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
