# Generated by Django 4.1.2 on 2022-10-24 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborg', '0004_mostpop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('game', models.CharField(default='dota', max_length=50)),
                ('date', models.TimeField(default=datetime.datetime(2022, 10, 24, 8, 58, 4, 685810, tzinfo=datetime.timezone.utc))),
                ('type', models.CharField(choices=[('download', 'download'), ('loaded', 'loaded')], max_length=10)),
            ],
        ),
    ]
