# Generated by Django 4.1.2 on 2022-10-25 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborg', '0007_top_alter_library_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='library',
            name='date',
            field=models.TimeField(default=datetime.datetime(2022, 10, 25, 10, 6, 43, 323554, tzinfo=datetime.timezone.utc)),
        ),
    ]
