# Generated by Django 4.1.2 on 2022-11-04 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborg', '0009_popular_alter_library_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('video', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='library',
            name='date',
            field=models.TimeField(default=datetime.datetime(2022, 11, 4, 9, 15, 40, 2610, tzinfo=datetime.timezone.utc)),
        ),
    ]
