# Generated by Django 4.1.2 on 2022-11-04 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborg', '0010_detailss_alter_library_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('pubg', 'pubg'), ('sandbox', 'sandbox')], max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='library',
            name='date',
            field=models.TimeField(default=datetime.datetime(2022, 11, 4, 9, 37, 42, 740406, tzinfo=datetime.timezone.utc)),
        ),
    ]
