# Generated by Django 4.1.2 on 2022-11-04 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborg', '0011_detal_alter_library_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomOutsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='')),
                ('img2', models.ImageField(upload_to='')),
                ('img3', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=300)),
                ('btn', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='library',
            name='date',
            field=models.TimeField(default=datetime.datetime(2022, 11, 4, 9, 53, 23, 983735, tzinfo=datetime.timezone.utc)),
        ),
    ]
